"""Force-field parameters for the UHS calcite / brine / H2 / cushion-gas model.

Units: LAMMPS `real` (kcal/mol, Angstrom, e, g/mol).
Cross terms: Lorentz-Berthelot (pair_modify mix arithmetic), the combining rule
used to fit SPC/E + Joung-Cheatham ions and the TraPPE gases.

Two levels of trust:
  * VERIFIED  - standard published values for water, ions and gases.
  * calcite   - read from ff/calcite.json; see the "verified" flag there.
"""
import json
import os

KB_KCAL = 0.0019872043  # kcal/(mol K), converts eps/k [K] -> kcal/mol

def eps_k(e_over_k):
    return e_over_k * KB_KCAL

# ---------------------------------------------------------------------------
# Atom types (fixed numbering, every type is always declared in the data file)
# name: (mass, charge, epsilon [kcal/mol], sigma [A], source)
# ---------------------------------------------------------------------------
FLUID_TYPES = {
    # SPC/E water: Berendsen, Grigera & Straatsma, J. Phys. Chem. 91 (1987) 6269.
    "Ow":  (15.9994, -0.8476, 0.15535, 3.16557, "SPC/E"),
    "Hw":  (1.008,    0.4238, 0.0,     0.0,     "SPC/E"),
    # Na+/Cl- for SPC/E: Joung & Cheatham, J. Phys. Chem. B 112 (2008) 9020.
    # sigma = 2 * Rmin/2 / 2^(1/6), Rmin/2 = 1.212 (Na), 2.711 (Cl) A.
    "Na":  (22.98977, 1.0, 0.3526418, 2.15954, "Joung-Cheatham 2008 (SPC/E)"),
    "Cl":  (35.453,  -1.0, 0.0127850, 4.83045, "Joung-Cheatham 2008 (SPC/E)"),
    # H2 single-site LJ: Buch, J. Chem. Phys. 100 (1994) 7610 (eps/k = 34.2 K).
    "H2":  (2.016,    0.0, eps_k(34.2), 2.96, "Buch 1994"),
    # CH4 united atom: TraPPE-UA, Martin & Siepmann, J. Phys. Chem. B 102 (1998) 2569.
    "CH4": (16.043,   0.0, eps_k(148.0), 3.73, "TraPPE-UA"),
    # CO2 rigid 3-site: TraPPE, Potoff & Siepmann, AIChE J. 47 (2001) 1676.
    "Cco2": (12.011,  0.70, eps_k(27.0), 2.80, "TraPPE CO2"),
    "Oco2": (15.9994, -0.35, eps_k(79.0), 3.05, "TraPPE CO2"),
    # N2 rigid 3-site (two N + charged centre site): TraPPE, Potoff & Siepmann 2001.
    # The centre site is massless in TraPPE; LAMMPS needs mass > 0, so it gets
    # 0.001 g/mol taken from the N atoms (total mass and inertia are unchanged
    # to 1e-4).
    "Nn2": (14.0062,  -0.482, eps_k(36.0), 3.31, "TraPPE N2"),
    "Mn2": (0.001,     0.964, 0.0,         0.0,  "TraPPE N2 (centre site)"),
}

# Rigid geometries (Angstrom / degrees)
GEOM = {
    "water_OH": 1.0, "water_HOH": 109.47,
    "co2_CO": 1.16,
    "n2_NN": 1.10,
}

# Order of all atom types in the LAMMPS data file
TYPE_ORDER = ["Ca", "Cc", "Oc", "Ow", "Hw", "Na", "Cl", "H2", "CH4",
              "Cco2", "Oco2", "Nn2", "Mn2"]
BOND_ORDER = ["Ow-Hw", "Cco2-Oco2", "Nn2-Mn2", "Cc-Oc"]
ANGLE_ORDER = ["Hw-Ow-Hw", "Oco2-Cco2-Oco2", "Oc-Cc-Oc"]


def load_calcite(path=None):
    path = path or os.path.join(os.path.dirname(__file__), "calcite.json")
    with open(path) as f:
        return json.load(f)


def all_types(calcite):
    t = dict(FLUID_TYPES)
    for name in ("Ca", "Cc", "Oc"):
        a = calcite["atoms"][name]
        t[name] = (a["mass"], a["charge"], a["epsilon_kcal"], a["sigma_A"],
                   calcite["name"])
    return t


def write_forcefield(path, calcite, cutoff=12.0):
    """Write the LAMMPS include file holding all pair/bond/angle coefficients."""
    types = all_types(calcite)
    tid = {n: i + 1 for i, n in enumerate(TYPE_ORDER)}
    lines = [
        "# Generated by build_system.py - do not edit by hand, edit ff/params.py",
        f"# calcite parameters: {calcite['name']}  verified={calcite['verified']}",
        f"pair_style      lj/cut/coul/long {cutoff:.1f}",
        "pair_modify     mix arithmetic",
        "bond_style      harmonic",
        "angle_style     harmonic",
        "kspace_style    pppm 1.0e-5",
        "special_bonds   lj/coul 0.0 0.0 0.0",
        "",
    ]
    for n in TYPE_ORDER:
        m, q, e, s, src = types[n]
        lines.append(f"pair_coeff {tid[n]:2d} {tid[n]:2d} {e:.6f} {s:.5f}   # {n:5s} {src}")
    # Bond / angle stiffness only matters for atoms that are integrated:
    # water is SHAKE-constrained, CO2/N2 are rigid bodies, calcite is frozen.
    # The values below just hold the reference geometry.
    lines += [
        "",
        f"bond_coeff  1 450.0 {GEOM['water_OH']}   # Ow-Hw  (SHAKE)",
        f"bond_coeff  2 1000.0 {GEOM['co2_CO']}    # C=O CO2 (rigid body)",
        f"bond_coeff  3 1000.0 {GEOM['n2_NN']/2:.3f}   # N-centre N2 (rigid body)",
        f"bond_coeff  4 {calcite['bond_CO']['k']} {calcite['bond_CO']['r0']}   # calcite C-O (frozen)",
        f"angle_coeff 1 55.0 {GEOM['water_HOH']}   # H-O-H  (SHAKE)",
        "angle_coeff 2 100.0 180.0   # O=C=O  (rigid body)",
        f"angle_coeff 3 {calcite['angle_OCO']['k']} {calcite['angle_OCO']['theta0']}   # calcite O-C-O (frozen)",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
