/* FPSO Console — explanations shown when a part of the field layout (or a panel) is tapped. [English, Arabic].
   Typical values are indicative ranges, not data of a specific unit. */
window.FPSO_INFO = (function () {
const E = (t, s, b) => ({ t, s, b });
return {
overview: E(['How an FPSO works', 'كيف تعمل وحدة FPSO'], ['From subsea wells to oil offloading', 'من الآبار تحت البحر إلى تفريغ النفط'], [
`<p>An <b>FPSO</b> (Floating Production, Storage and Offloading unit) is a ship-shaped facility moored above a subsea field. It brings well fluids up through risers, separates oil, gas and water, stores the stabilised crude in its hull, and offloads it to shuttle tankers. It is used where pipelines to shore are impractical: deep water, remote or small fields.</p>
<ol><li>Reservoir → subsea wells (trees, chokes)</li><li>Flowlines → manifold → risers → turret and swivel</li><li>Topsides: separation, gas compression, water treatment, power</li><li>Crude stored in cargo tanks → offloaded to a shuttle tanker</li><li>Gas: fuel, gas lift, export or reinjection; produced water treated; seawater injected for pressure support</li></ol>
<p class="note">Tap any part of the drawing, or any parameter, for its explanation. Typical sizes: storage around 1–2 million bbl, production from tens to a few hundred thousand bbl/d.</p>`,
`<p><b>الـ FPSO</b> (وحدة إنتاج وتخزين وتفريغ عائمة) منشأة على شكل سفينة مثبّتة فوق حقل تحت البحر. ترفع موائع الآبار عبر الـ risers، وتفصل النفط والغاز والماء، وتخزّن النفط المستقر في خزانات بدنها، ثم تفرّغه إلى ناقلات مكوكية. تُستخدم حيث يصعب مدّ خطوط أنابيب إلى الشاطئ: المياه العميقة، أو الحقول البعيدة أو الصغيرة.</p>
<ol><li>المكمن ← الآبار تحت البحر (الـ trees والـ chokes)</li><li>الـ flowlines ← الـ manifold ← الـ risers ← الـ turret والـ swivel</li><li>المنشآت العلوية: الفصل، وضغط الغاز، ومعالجة الماء، والطاقة</li><li>النفط يُخزَّن في خزانات الحمولة ← يُفرَّغ إلى ناقلة مكوكية</li><li>الغاز: وقود، و gas lift، وتصدير أو إعادة حقن؛ والماء المنتج يُعالَج؛ وماء البحر يُحقن لدعم الضغط</li></ol>
<p class="note">اضغط على أي جزء من الرسم أو أي بارامتر لترى شرحه. أحجام نموذجية: تخزين بحدود 1–2 مليون برميل، وإنتاج من عشرات إلى بضع مئات آلاف برميل يومياً.</p>`]),
reservoir: E(['Reservoir', 'المكمن'], ['Oil, gas and water in porous rock', 'نفط وغاز وماء في صخر مسامي'], [
`<p>Hydrocarbons sit in the pores of the rock above the <b>oil–water contact (OWC)</b>. Reservoir pressure pushes fluid into the wells. The rate each well can deliver is its <b>inflow performance (IPR)</b>: straight line above the bubble point, Vogel curve below it.</p>
<ul><li><b>Bubble point (Pb)</b>: below it, gas comes out of solution in the reservoir. GOR rises and oil recovery suffers.</li><li><b>Voidage replacement ratio (VRR)</b> = injected volume / produced volume at reservoir conditions. VRR ≈ 1 holds pressure; &lt; 1 lets it fall.</li><li><b>Water cut</b> rises with time as injected or aquifer water reaches the wells.</li></ul>
<p class="note">In the simulator: a material balance with total compressibility. Use the “fast reservoir depletion” scenario to see pressure fall without water injection.</p>`,
`<p>توجد الهيدروكربونات في مسام الصخر فوق <b>سطح تماس النفط والماء (OWC)</b>. ضغط المكمن يدفع المائع إلى الآبار. المعدل الذي يعطيه كل بئر هو <b>أداء التدفق الداخلي (IPR)</b>: خط مستقيم فوق نقطة الفقاعة، ومنحنى Vogel تحتها.</p>
<ul><li><b>نقطة الفقاعة (Pb)</b>: تحتها يخرج الغاز من المحلول داخل المكمن، فيرتفع الـ GOR ويتضرر الاستخلاص.</li><li><b>نسبة تعويض الفراغ (VRR)</b> = الحجم المحقون / الحجم المنتج بظروف المكمن. VRR ≈ 1 يحافظ على الضغط؛ و &lt; 1 يتركه ينخفض.</li><li><b>نسبة الماء (water cut)</b> تزداد مع الزمن عندما يصل ماء الحقن أو الطبقة المائية إلى الآبار.</li></ul>
<p class="note">في المحاكي: موازنة مادية مع الانضغاطية الكلية. استخدم سيناريو "استنزاف سريع للمكمن" لترى انخفاض الضغط دون حقن ماء.</p>`]),
wells: E(['Subsea wells & trees', 'الآبار وأشجار الإنتاج تحت البحر'], ['Control production from the reservoir', 'تتحكم بالإنتاج من المكمن'], [
`<p>Each well has a <b>subsea christmas tree</b> on the seabed. It carries the master and wing valves, a <b>subsea choke</b>, and pressure and temperature sensors. A safety valve sits down the tubing. It is all controlled from the FPSO through an <b>umbilical</b> (hydraulics, power, signals, chemicals).</p>
<ul><li><b>Choke</b>: sets the rate. Opening it lowers the wellhead pressure (WHP) and raises flow.</li><li><b>Nodal analysis</b>: the rate is where the reservoir inflow (IPR) meets the outflow (tubing + choke + manifold back-pressure).</li><li><b>Gas lift</b>: injecting gas into the tubing lightens the fluid column and revives wells with a high water cut. Too much lift gas adds friction, so there is an optimum.</li><li>“Not flowing” means the reservoir pressure cannot lift the column against the back-pressure.</li></ul>`,
`<p>لكل بئر <b>شجرة إنتاج (christmas tree)</b> على قاع البحر. تحمل صمامات master و wing، و<b>choke تحت البحر</b>، وحساسات للضغط والحرارة. وفي أنبوب الإنتاج صمام أمان. كل ذلك يُتحكَّم به من الـ FPSO عبر <b>umbilical</b> (هيدروليك، وكهرباء، وإشارات، وكيماويات).</p>
<ul><li><b>الـ Choke</b>: يحدد المعدل. فتحه يخفض ضغط رأس البئر (WHP) ويرفع التدفق.</li><li><b>التحليل العُقدي (nodal analysis)</b>: المعدل هو نقطة التقاء تدفق المكمن الداخل (IPR) مع منحنى الخروج (الأنبوب + الـ choke + الضغط المعاكس للـ manifold).</li><li><b>رفع بالغاز (gas lift)</b>: حقن غاز في أنبوب الإنتاج يخفّف عمود المائع ويعيد الحياة للآبار ذات نسبة الماء العالية. وزيادة غاز الرفع أكثر من اللازم تضيف احتكاكاً، فهناك قيمة مثلى.</li><li>"لا يتدفق" تعني أن ضغط المكمن لا يكفي لرفع العمود أمام الضغط المعاكس.</li></ul>`]),
flowlines: E(['Flowlines & hydrates', 'الـ Flowlines والهيدرات'], ['Connect wells to the manifold', 'تربط الآبار بالـ manifold'], [
`<p>Insulated flowlines carry the well fluids on the seabed, where the water is near 4 °C. While flowing, the fluid stays warm. After a shutdown it cools. When the temperature falls below the <b>hydrate curve</b> at that pressure, gas and water can form <b>ice-like hydrate plugs</b>.</p>
<ul><li>The <b>cooldown time</b> is how long you have after a shutdown before reaching the hydrate zone.</li><li>Protection: inject <b>MEG/methanol</b> (this shifts the hydrate curve), depressurise the line, or restart before the cooldown time runs out.</li><li>Other flow-assurance issues: wax, asphaltenes, scale, slugging.</li></ul>
<p class="note">In the simulator: the hydrate curve is a simplified fit. MEG lowers it by a fixed amount.</p>`,
`<p>خطوط معزولة تنقل موائع الآبار على قاع البحر، حيث حرارة الماء قرب 4 °م. أثناء التدفق يبقى المائع دافئاً، وبعد الإيقاف يبرد. عندما تنخفض حرارته تحت <b>منحنى الهيدرات</b> عند ذلك الضغط، يمكن أن يكوّن الغاز والماء <b>سدادات هيدرات تشبه الجليد</b>.</p>
<ul><li><b>زمن التبريد (cooldown)</b> هو الوقت المتاح بعد الإيقاف قبل الدخول في منطقة الهيدرات.</li><li>الحماية: حقن <b>MEG/ميثانول</b> (يزيح منحنى الهيدرات)، أو تخفيض ضغط الخط، أو إعادة التشغيل قبل انتهاء زمن التبريد.</li><li>تحديات أخرى لضمان التدفق: الشمع، والأسفلتين، والترسبات، والـ slugging.</li></ul>
<p class="note">في المحاكي: منحنى الهيدرات تقريب مبسّط، والـ MEG يخفضه بمقدار ثابت.</p>`]),
manifold: E(['Subsea manifold', 'الـ Manifold تحت البحر'], ['Combines production from wells', 'يجمع إنتاج الآبار'], [
`<p>A seabed structure of headers and valves. It gathers the flowlines from several wells into production headers that feed the risers. It can route a well to a test line and distribute gas lift, water injection and chemicals.</p>
<ul><li><b>Manifold pressure</b> = separator pressure + riser hydrostatic head + friction. It is the back-pressure the wells must overcome.</li><li>Lower manifold pressure (lighter riser, lower separator pressure) means more production.</li></ul>`,
`<p>هيكل على قاع البحر من مجمّعات (headers) وصمامات. يجمع الـ flowlines القادمة من عدة آبار في مجمّعات إنتاج تغذّي الـ risers. ويمكنه توجيه بئر إلى خط الاختبار، وتوزيع غاز الرفع وماء الحقن والكيماويات.</p>
<ul><li><b>ضغط الـ manifold</b> = ضغط الفاصل + الضغط الهيدروستاتيكي في الـ riser + الاحتكاك. وهو الضغط المعاكس الذي يجب أن تتغلب عليه الآبار.</li><li>ضغط manifold أقل (riser أخف، أو ضغط فاصل أقل) يعني إنتاجاً أكبر.</li></ul>`]),
risers: E(['Risers', 'الـ Risers'], ['Well fluids to the FPSO', 'موائع الآبار إلى الـ FPSO'], [
`<p>Flexible pipes from the seabed up to the turret. They carry production, gas lift and water injection. Here they hang in a <b>lazy-wave</b> shape: buoyancy modules make a hump that absorbs the vessel's motions and offset.</p>
<ul><li>The riser's hydrostatic head is the largest part of the back-pressure in deep water.</li><li><b>Severe slugging</b>: at low rates, liquid collects at the riser base and is then pushed up in large slugs. Pressure and level cycle at the separator. Remedies: more rate, gas lift at the riser base, a topside choke.</li><li>The vessel's offset must stay within the riser's design limits.</li></ul>`,
`<p>أنابيب مرنة من قاع البحر حتى الـ turret، تنقل الإنتاج وغاز الرفع وماء الحقن. هنا تتدلى بشكل <b>lazy-wave</b>: وحدات طفو تصنع حدبة تمتص حركة السفينة وإزاحتها.</p>
<ul><li>الضغط الهيدروستاتيكي في الـ riser هو أكبر جزء من الضغط المعاكس في المياه العميقة.</li><li><b>الـ slugging الشديد</b>: عند المعدلات المنخفضة يتجمع السائل عند قاعدة الـ riser ثم يندفع إلى الأعلى في دفعات كبيرة، فيتذبذب الضغط والمستوى في الفاصل. العلاج: معدل أعلى، أو gas lift عند قاعدة الـ riser، أو choke على السطح.</li><li>يجب أن تبقى إزاحة السفينة ضمن حدود تصميم الـ risers.</li></ul>`]),
turret: E(['Turret mooring', 'التثبيت بالـ Turret'], ['Keeps the FPSO on station', 'يُبقي الـ FPSO في موقعها'], [
`<p>The mooring lines (chain–wire–chain, in bundles, to anchors or piles) are attached to a <b>turret</b> that is fixed to the seabed. The ship rotates freely around it: <b>weathervaning</b>. It turns its bow into the combined wind, waves and current, which minimises loads. A <b>swivel stack</b> passes fluids, power and signals from the fixed turret to the rotating ship.</p>
<ul><li><b>Offset</b> = horizontal excursion. It is kept to a few percent of water depth to protect the risers.</li><li><b>Line tension</b> is compared with the minimum breaking load (MBL). The design keeps the system safe even with one line broken.</li></ul>
<p class="note">In the simulator: quasi-static mooring stiffness plus a dynamic wave term; the plan view exaggerates the offset ×3. Try the “storm” and “mooring line failure” scenarios.</p>`,
`<p>خطوط التثبيت (سلسلة–سلك–سلسلة، في مجموعات، إلى مراسٍ أو أوتاد) مربوطة بـ <b>turret</b> ثابت بالنسبة لقاع البحر. وتدور السفينة حوله بحرية: <b>weathervaning</b>، فتوجّه مقدمتها نحو محصلة الرياح والأمواج والتيار، فتقل الأحمال. و<b>الـ swivel</b> ينقل الموائع والكهرباء والإشارات من الـ turret الثابت إلى السفينة الدوّارة.</p>
<ul><li><b>الإزاحة (offset)</b> = الانحراف الأفقي، وتُبقى ضمن نسبة صغيرة من عمق الماء لحماية الـ risers.</li><li><b>شدّ الخطوط</b> يُقارن بحمل الكسر الأدنى (MBL). والتصميم يُبقي النظام آمناً حتى مع انقطاع خط واحد.</li></ul>
<p class="note">في المحاكي: صلابة تثبيت شبه ساكنة مع حد ديناميكي للأمواج، والمنظر العلوي يكبّر الإزاحة ×3. جرّب سيناريو "عاصفة" و"انقطاع خط تثبيت".</p>`]),
separator: E(['Processing — HP separator', 'المعالجة — الفاصل عالي الضغط'], ['Separates oil, gas and water', 'يفصل النفط والغاز والماء'], [
`<p>A large horizontal 3-phase vessel. Gas rises to the top, water settles at the bottom, and oil floats between them. Liquid retention is a few minutes. Three controllers keep it steady:</p>
<ul><li><b>Pressure control</b>: gas is sent to the compressors. A PCV sends excess to the flare and a PSV protects the vessel.</li><li><b>Liquid level</b> (oil outlet) and <b>interface level</b> (water outlet). A high-high level trips the wells (process shutdown).</li><li>Downstream: heating, LP separation and stabilisation bring the crude to <b>export spec</b>, commonly BS&amp;W ≤ 0.5 % and a vapour-pressure limit, before storage.</li></ul>
<p class="note">Lower separator pressure gives more production (less back-pressure) but costs more compression power. Try changing the pressure set-point.</p>`,
`<p>وعاء أفقي كبير ثلاثي الأطوار: يصعد الغاز إلى الأعلى، ويترسّب الماء في الأسفل، ويطفو النفط بينهما. زمن بقاء السائل بضع دقائق، وتحافظ ثلاثة متحكمات على استقراره:</p>
<ul><li><b>التحكم بالضغط</b>: يُرسل الغاز إلى الضواغط. وصمام PCV يرسل الفائض إلى الشعلة، وصمام PSV يحمي الوعاء.</li><li><b>مستوى السائل</b> (مخرج النفط) و<b>مستوى السطح الفاصل</b> (مخرج الماء). والمستوى المرتفع جداً (high-high) يوقف الآبار (process shutdown).</li><li>بعده: تسخين، وفصل منخفض الضغط، وتثبيت، حتى يصل النفط إلى <b>مواصفة التصدير</b> قبل التخزين، وعادةً BS&amp;W ≤ 0.5 % وحدّ لضغط البخار.</li></ul>
<p class="note">ضغط فاصل أقل يعطي إنتاجاً أكبر (ضغط معاكس أقل) لكنه يكلّف طاقة ضغط أكبر. جرّب تغيير قيمة الضغط المطلوبة.</p>`]),
compression: E(['Gas compression', 'ضغط الغاز'], ['Export, lift, fuel and reinjection gas', 'غاز التصدير والرفع والوقود وإعادة الحقن'], [
`<p>Separator gas is compressed in several stages, with coolers and scrubbers between stages, and dehydrated (glycol/TEG) for:</p>
<ul><li><b>Fuel gas</b> for the gas-turbine generators: first priority.</li><li><b>Gas lift</b> to the wells.</li><li><b>Export</b> through a pipeline, or <b>reinjection</b> into the reservoir, which supports pressure and stores gas when there is no export route.</li></ul>
<p>Compressor power follows the adiabatic equation: it rises with gas rate and pressure ratio. A <b>train trip</b> sends the surplus gas to the <b>flare</b>. Operators then cut back the high-GOR wells to stop flaring.</p>
<p class="note">The simulator has 2 × 50 % trains. Try the “compressor trip” scenario.</p>`,
`<p>يُضغط غاز الفاصل على عدة مراحل، مع مبرّدات وفواصل (scrubbers) بين المراحل، ويُجفَّف (glycol/TEG)، ثم يُستخدم في:</p>
<ul><li><b>غاز الوقود</b> لمولدات التوربينات الغازية: الأولوية الأولى.</li><li><b>غاز الرفع</b> للآبار.</li><li><b>التصدير</b> عبر خط أنابيب، أو <b>إعادة الحقن</b> في المكمن، فتدعم الضغط وتخزّن الغاز عند عدم وجود طريق للتصدير.</li></ul>
<p>قدرة الضاغط تتبع المعادلة الأديباتية: تزداد مع معدل الغاز ونسبة الضغط. و<b>توقف قطار ضاغط</b> يرسل الغاز الفائض إلى <b>الشعلة</b>، فيخفّض المشغّلون إنتاج الآبار ذات الـ GOR العالي لإيقاف الحرق.</p>
<p class="note">في المحاكي قطاران بسعة 50 % لكل منهما. جرّب سيناريو "توقف الضاغط".</p>`]),
flare: E(['Flare', 'الشعلة'], ['Safe disposal of excess gas', 'التخلص الآمن من الغاز الفائض'], [
`<p>The flare is a <b>safety system</b>. It burns gas released by pressure control, relief valves (PSV) and <b>blowdown</b> during an emergency shutdown. A small continuous purge and pilot keep it ready.</p>
<ul><li>Routine flaring wastes resources and is increasingly regulated. High flaring is an alarm here.</li><li>Large flares appear on a compressor trip, during blowdown, or when gas exceeds compression and export capacity.</li></ul>`,
`<p>الشعلة <b>نظام أمان</b>: تحرق الغاز المنطلق من التحكم بالضغط، ومن صمامات الأمان (PSV)، ومن <b>التنفيس (blowdown)</b> أثناء الإيقاف الطارئ. وتُبقيها جاهزة كميةُ تطهير مستمرة صغيرة مع لهب دليلي.</p>
<ul><li>الحرق الروتيني هدر للموارد ويخضع لقيود متزايدة، والحرق المرتفع إنذار هنا.</li><li>تظهر الشعلات الكبيرة عند توقف ضاغط، أو أثناء التنفيس، أو عندما يتجاوز الغاز سعة الضغط والتصدير.</li></ul>`]),
water: E(['Produced water treatment', 'معالجة الماء المنتج'], ['Clean water before discharge', 'تنظيف الماء قبل التصريف'], [
`<p>Water from the separator passes through <b>hydrocyclones</b> and a degasser or flotation unit. These remove oil droplets until the <b>oil-in-water (OIW)</b> content meets the discharge limit. The limit is set by the regulator; around 30 mg/L as an average is common (e.g. OSPAR). The water is then discharged overboard or reinjected.</p>
<ul><li>OIW rises with hydraulic overload, interface upsets in the separator, and fouling.</li><li>As water cut grows, water handling often becomes the bottleneck of an ageing field.</li></ul>`,
`<p>يمر ماء الفاصل عبر <b>الـ hydrocyclones</b> ووحدة نزع الغاز أو التعويم. وهي تزيل قطرات النفط حتى يحقق محتوى <b>النفط في الماء (OIW)</b> حدّ التصريف. يحدد الحدَّ المنظِّم، وحدود بحدود 30 mg/L كمعدل شائعة (مثل OSPAR). ثم يُصرف الماء إلى البحر أو يُعاد حقنه.</p>
<ul><li>يرتفع الـ OIW مع زيادة الحمل الهيدروليكي، واضطراب السطح الفاصل في الفاصل، والاتساخ.</li><li>مع ازدياد نسبة الماء، تصبح معالجة الماء غالباً عنق الزجاجة في الحقول القديمة.</li></ul>`]),
injection: E(['Water injection', 'حقن الماء'], ['Pressure support for the reservoir', 'دعم ضغط المكمن'], [
`<p>Seawater is filtered and deaerated, often sulphate-reduced to avoid scale and souring. It is then pumped at high pressure down injection wells below the oil zone. This maintains reservoir pressure and sweeps oil towards the producers.</p>
<ul><li>Track the <b>VRR</b>: about 1 keeps the pressure stable.</li><li>Water injection pumps are one of the largest power users after gas compression.</li></ul>`,
`<p>يُرشَّح ماء البحر ويُنزع منه الأكسجين، وكثيراً ما تُخفَّض كبريتاته لتجنّب الترسبات والتحمّض. ثم يُضخ بضغط عالٍ في آبار حقن تحت منطقة النفط، فيحافظ على ضغط المكمن ويدفع النفط نحو آبار الإنتاج.</p>
<ul><li>راقب <b>الـ VRR</b>: قيمة قريبة من 1 تُبقي الضغط مستقراً.</li><li>مضخات حقن الماء من أكبر مستهلكي الطاقة بعد ضغط الغاز.</li></ul>`]),
power: E(['Power generation', 'توليد الطاقة'], ['Gas-turbine generators', 'مولدات بتوربينات غازية'], [
`<p>Several dual-fuel gas-turbine generators, with N+1 redundancy, burn the field's own <b>fuel gas</b>. They switch to <b>diesel</b> when gas is short. Gas compression and water injection are the largest loads.</p>
<ul><li>Fuel gas ≈ power ÷ (turbine efficiency × gas heating value).</li><li>If demand exceeds the available generation, load shedding trips equipment.</li></ul>`,
`<p>عدة مولدات بتوربينات غازية ثنائية الوقود، مع احتياط N+1، تحرق <b>غاز الوقود</b> من الحقل نفسه، وتتحول إلى <b>الديزل</b> عند نقص الغاز. ضغط الغاز وحقن الماء هما أكبر الأحمال.</p>
<ul><li>غاز الوقود ≈ القدرة ÷ (كفاءة التوربين × القيمة الحرارية للغاز).</li><li>إذا تجاوز الطلب التوليدَ المتاح، يفصل نظام تخفيف الأحمال (load shedding) بعض المعدات.</li></ul>`]),
storage: E(['Crude oil storage', 'تخزين النفط الخام'], ['Stored in the hull tanks', 'يُخزَّن في خزانات البدن'], [
`<p>Stabilised crude is stored in the cargo tanks of the hull, under an <b>inert-gas blanket</b> so that no explosive atmosphere forms. As tanks fill, the <b>draft</b> increases. Storage typically holds one or two weeks of production, so offloading must be planned before the tanks are full. When they are full, production stops.</p>`,
`<p>يُخزَّن النفط المستقر في خزانات الحمولة داخل البدن، تحت <b>غطاء من الغاز الخامل</b> حتى لا يتكوّن جو قابل للانفجار. ومع امتلاء الخزانات يزداد <b>الغاطس</b>. يتسع التخزين عادةً لإنتاج أسبوع أو أسبوعين، لذا يجب التخطيط للتفريغ قبل الامتلاء. وعند امتلاء الخزانات يتوقف الإنتاج.</p>`]),
tanker: E(['Shuttle tanker & offloading', 'الناقلة المكوكية والتفريغ'], ['Receives crude oil', 'تستلم النفط الخام'], [
`<p>In <b>tandem offloading</b>, a dynamically positioned shuttle tanker approaches the stern. It connects a <b>hawser</b> (mooring rope) and a <b>floating hose</b>, and receives a parcel of crude, often around 0.5–1 million bbl, over about a day.</p>
<ul><li>Sequence: approach → hook-up → offloading → disconnect → depart.</li><li>Offloading is limited by weather (significant wave height). Above the limit it stops; in a storm the tanker disconnects in an emergency.</li></ul>`,
`<p>في <b>التفريغ الترادفي (tandem)</b> تقترب ناقلة مكوكية ذات تموضع ديناميكي (DP) من مؤخرة الـ FPSO. تربط <b>حبل قطر (hawser)</b> و<b>خرطوماً عائماً</b>، وتستلم شحنة نفط، غالباً بحدود 0.5–1 مليون برميل، خلال يوم تقريباً.</p>
<ul><li>التسلسل: اقتراب ← ربط ← تفريغ ← فصل ← مغادرة.</li><li>التفريغ محدود بالطقس (ارتفاع الموج المعنوي). فوق الحد يتوقف، وفي العاصفة تنفصل الناقلة فصلاً طارئاً.</li></ul>`]),
helideck: E(['Helideck & helicopter logistics', 'مهبط المروحيات والنقل الجوي'], ['Crew change, weather limits, location', 'تبديل الطاقم، حدود الطقس، الموقع'], [
`<p>Crews (typically 100–150 people on board) rotate by <b>helicopter</b>, commonly on 2–3-week shifts. The <b>helideck</b> is usually placed on top of the <b>accommodation block</b>, which on a turret-moored FPSO is at the stern, far from the turret, the flare and the hydrocarbon process. That keeps the approach path clear of hot exhaust and gas.</p>
<ul><li>Operations follow published offshore helideck standards. In the UK these are CAP 437 (Civil Aviation Authority); internationally, see the ICAO and OGP/IOGP aviation guidance. They set the D-value (deck size), the obstacle-free sector, lighting, and limits on deck motion (pitch, roll, heave) and wind.</li><li>A flight is cancelled when the wind or the deck motion is above limits, and during an ESD.</li><li>POB (persons on board) is tracked for every flight; it must not exceed lifeboat capacity.</li></ul>
<p class="note">In this model the limits are illustrative: 30 m/s wind and Hs 5 m. The inbound and outbound legs take 15 min each, with 30 min on deck. Real limits depend on the aircraft type and the vessel's motion criteria.</p>`,
`<p>يتبدّل الطاقم (عادةً 100–150 شخصاً على المتن) <b>بالمروحية</b>، وغالباً بمناوبات من 2–3 أسابيع. يوضع <b>مهبط المروحيات</b> عادةً فوق <b>مبنى السكن</b>. في الـ FPSO المثبّتة بـ turret يكون هذا المبنى عند المؤخرة، بعيداً عن الـ turret والشعلة ووحدات معالجة الهيدروكربونات، فيبقى مسار الاقتراب خالياً من العادم الساخن والغاز.</p>
<ul><li>تتبع العمليات معايير منشورة لمهابط المروحيات البحرية. في بريطانيا هي CAP 437 (هيئة الطيران المدني)، ودولياً إرشادات ICAO و OGP/IOGP للطيران. تحدد هذه المعايير الـ D-value (حجم المهبط)، والقطاع الخالي من العوائق، والإضاءة، وحدود حركة السطح (pitch, roll, heave) والرياح.</li><li>تُلغى الرحلة إذا تجاوزت الرياح أو حركة السطح الحدود، وأثناء الـ ESD.</li><li>يُسجَّل الـ POB (عدد الأشخاص على المتن) مع كل رحلة، ويجب ألا يتجاوز سعة قوارب النجاة.</li></ul>
<p class="note">الحدود في هذا النموذج توضيحية: رياح 30 m/s و Hs 5 m. يستغرق الذهاب والإياب 15 دقيقة لكل منهما، والبقاء على السطح 30 دقيقة. الحدود الحقيقية تعتمد على نوع المروحية ومعايير حركة السفينة.</p>`]),
rov: E(['ROV — remotely operated vehicle', 'الـ ROV — مركبة تُشغَّل عن بُعد'], ['The eyes and hands under the FPSO', 'العين واليد تحت الـ FPSO'], [
`<p>A <b>work-class ROV</b> is launched from the FPSO (or a support vessel) by a <b>LARS</b> (launch and recovery system) inside a cage or <b>TMS</b> (tether management system). From the TMS it flies on a tether that carries its power, video and control. Pilots in a control van fly it with live cameras, lights, sonar and two manipulator arms.</p>
<ul><li><b>Inspection:</b> the hull and its anodes, the turret chain table, mooring chain and touchdown, riser buoyancy modules, and the riser base.</li><li><b>Intervention:</b> operating valves through the <b>ROV panel</b> on trees and manifolds (torque tools, hot-stabs), changing choke inserts, and connecting jumpers.</li><li>A typical work-class system is rated to 3000–4000 m water depth.</li></ul>
<p class="note">The camera here re-renders the same live model, magnified. Lights and darkness increase with depth for realism, and the turbidity ("marine snow") is cosmetic.</p>`,
`<p>يُنزَل <b>الـ ROV من فئة work-class</b> من الـ FPSO (أو من سفينة دعم) بنظام <b>LARS</b> (نظام الإنزال والاسترجاع) داخل قفص أو <b>TMS</b> (نظام إدارة الكابل). من الـ TMS يسبح على كابل (tether) ينقل الطاقة والفيديو والتحكم. يقوده الطيارون من غرفة تحكم بكاميرات حية وأضواء وسونار وذراعين آليين.</p>
<ul><li><b>الفحص:</b> البدن وأقطاب الحماية (anodes)، والـ chain table في الـ turret، وسلاسل التثبيت ونقطة الملامسة، ووحدات طفو الـ riser، وقاعدة الـ riser.</li><li><b>التدخل:</b> تشغيل الصمامات عبر <b>لوحة الـ ROV</b> على الـ trees والـ manifolds (أدوات عزم، hot-stabs)، وتغيير قطع الـ choke، وتوصيل الـ jumpers.</li><li>نظام work-class نموذجي مصمم لأعماق 3000–4000 m.</li></ul>
<p class="note">الكاميرا هنا تعرض النموذج الحي نفسه مكبّراً. الإضاءة والظلام يزدادان مع العمق للواقعية، والعكارة ("الثلج البحري") تجميلية فقط.</p>`]),
crew_oim: E(['OIM — Offshore Installation Manager', 'الـ OIM — مدير المنشأة البحرية'], ['WALEID ALOBAID · accommodation, OIM office', 'WALEID ALOBAID · السكن، مكتب المدير'], [
`<p>The <b>OIM</b> is the most senior person on board, in this simulator <b>WALEID ALOBAID</b>. He has overall authority for the safety of everyone on board and of the installation, and for production and emergency response.</p><ul><li>Approves high-risk work through the <b>permit-to-work</b> system and leads the daily planning meeting.</li><li>In an emergency (ESD, fire, gas release, abandonment) he commands the response from the emergency control room and decides on mustering or evacuation.</li><li>Is the single point of contact with the onshore management and the authorities.</li></ul><p class="note">Typical offshore pattern: 12-hour shifts, rotations of 2–3 weeks on / 2–3 weeks off. Crew change is by helicopter.</p>`,
`<p>الـ <b>OIM</b> هو أعلى مسؤول على المنشأة، وهو في هذا المحاكي <b>WALEID ALOBAID</b>. يتولى السلطة الكاملة على سلامة كل من على المتن وسلامة المنشأة، وعلى الإنتاج والاستجابة للطوارئ.</p><ul><li>يوافق على الأعمال عالية الخطورة عبر نظام <b>تصاريح العمل (permit to work)</b>، ويقود اجتماع التخطيط اليومي.</li><li>في الطوارئ (ESD، حريق، تسرب غاز، إخلاء) يقود الاستجابة من غرفة التحكم بالطوارئ، ويقرر التجمّع أو الإخلاء.</li><li>هو نقطة الاتصال الوحيدة مع الإدارة على البر ومع الجهات الرسمية.</li></ul><p class="note">النمط المعتاد في البحر: مناوبات 12 ساعة، ودورات 2–3 أسابيع عمل يقابلها 2–3 أسابيع راحة. ويتم تبديل الطاقم بالمروحية.</p>`]),
crew_cro: E(['Control room operators (CRO)', 'مشغلو غرفة التحكم (CRO)'], ['Central control room (CCR)', 'غرفة التحكم المركزية (CCR)'], [
`<p>CROs watch the plant 24 hours a day on the <b>DCS / ICSS</b> screens. They acknowledge and handle alarms; open and close wells and chokes; adjust separator and compressor set-points; and start and stop equipment. They coordinate the field operators by radio.</p><ul><li>They are the first to see an upset (high level, trip, gas detection) and to start a PSD or ESD.</li><li>They isolate equipment for maintenance under the permit-to-work system.</li></ul><p class="note">In this simulator, <b>you</b> are the CRO: the panels on this page are your consoles.</p>`,
`<p>يراقب مشغلو غرفة التحكم المنشأة على مدار 24 ساعة عبر شاشات <b>DCS / ICSS</b>. يستقبلون الإنذارات ويعالجونها، ويفتحون الآبار والـ chokes ويغلقونها، ويعدّلون نقاط ضبط الفاصل والضواغط، ويشغّلون المعدات ويوقفونها. وينسّقون مع المشغلين الميدانيين بالراديو.</p><ul><li>هم أول من يرى أي خلل (مستوى مرتفع، توقف، كشف غاز)، وأول من يبدأ PSD أو ESD.</li><li>يعزلون المعدات للصيانة ضمن نظام تصاريح العمل.</li></ul><p class="note">في هذا المحاكي <b>أنت</b> مشغل غرفة التحكم: لوحات هذه الصفحة هي شاشاتك.</p>`]),
crew_proc: E(['Process / production engineer', 'مهندس العمليات / الإنتاج'], ['Separation module and the control room', 'وحدة الفصل وغرفة التحكم'], [
`<p>Keeps production optimal and stable:</p><ul><li>Well tests, choke and gas-lift optimisation.</li><li>Separator pressure and level set-points; chemical injection (demulsifier, antifoam, scale and hydrate inhibitors such as MEG).</li><li>Crude quality (BS&amp;W) and flaring.</li><li>Daily production reports and troubleshooting upsets such as slugging and foaming.</li></ul><p>Field (area) operators make rounds on the modules: they check gauges, take readings and line up valves.</p>`,
`<p>يحافظ على إنتاج أمثل ومستقر:</p><ul><li>اختبارات الآبار، وتحسين الـ chokes والـ gas lift.</li><li>نقاط ضبط ضغط الفاصل ومستواه، وحقن الكيماويات (كاسر الاستحلاب، مضاد الرغوة، مثبطات القشور والهيدرات مثل MEG).</li><li>جودة النفط (BS&amp;W) والحرق.</li><li>تقارير الإنتاج اليومية، ومعالجة الاضطرابات مثل الـ slugging والرغوة.</li></ul><p>يتجوّل المشغلون الميدانيون على الوحدات: يفحصون العدادات ويأخذون القراءات ويضبطون مسارات الصمامات.</p>`]),
crew_mech: E(['Mechanical technician (rotating equipment)', 'فني ميكانيك (المعدات الدوّارة)'], ['Gas compression module', 'وحدة ضغط الغاز'], [
`<p>Maintains compressors, pumps and turbines:</p><ul><li>Vibration and bearing-temperature monitoring, lube-oil and dry-gas seal systems.</li><li>Planned maintenance and overhauls.</li><li>After a trip, finds the cause together with the CRO before a restart.</li></ul><p class="note">Try it: Instructor → "Compressor train A trip", then watch the flare and restart the train.</p>`,
`<p>يصون الضواغط والمضخات والتوربينات:</p><ul><li>مراقبة الاهتزاز وحرارة المحامل، وأنظمة زيت التزييت وموانع التسرب الغازية الجافة (dry gas seals).</li><li>الصيانة المخططة والعَمرات.</li><li>بعد أي توقف (trip) يحدد السبب مع مشغل غرفة التحكم قبل إعادة التشغيل.</li></ul><p class="note">جرّب: المدرّب ← "توقف قطار الضاغط A"، ثم راقب الشعلة وأعد تشغيل القطار.</p>`]),
crew_elec: E(['Electrical & instrument (E&I) technician', 'فني الكهرباء والأجهزة (E&I)'], ['Power generation module and the switchboards', 'وحدة توليد الطاقة ولوحات التوزيع'], [
`<p>Looks after generation and distribution of power: gas-turbine generators, switchboards and UPS. Also maintains the instruments: pressure and level transmitters, control valves, analysers. Tests the safety systems (fire &amp; gas detection, ESD valves) on a schedule.</p><p class="note">When fuel gas is short, the turbines switch to diesel. Load shedding protects the essential consumers.</p>`,
`<p>يتولى توليد الطاقة وتوزيعها: مولدات التوربينات الغازية، ولوحات التوزيع، والـ UPS. ويصون الأجهزة أيضاً: مرسلات الضغط والمستوى، وصمامات التحكم، والمحللات. ويختبر أنظمة السلامة (كشف الحريق والغاز، صمامات ESD) وفق جدول.</p><p class="note">عند نقص غاز الوقود تتحول التوربينات إلى الديزل، ويحمي فصل الأحمال (load shedding) المستهلكين الأساسيين.</p>`]),
crew_lab: E(['Laboratory technician (chemist)', 'فني المختبر (كيميائي)'], ['Laboratory and the water-treatment module', 'المختبر ووحدة معالجة الماء'], [
`<p>Samples and analyses the main streams:</p><ul><li>Crude oil: BS&amp;W and salt content, against the export specification.</li><li>Produced water: oil-in-water before discharge to sea. Discharge is regulated; in the North-East Atlantic (OSPAR), for example, the performance standard is 30 mg/L dispersed oil.</li><li>Injection water: oxygen and solids. Also corrosion coupons and chemical dosing rates.</li></ul>`,
`<p>يأخذ عينات من التيارات الرئيسية ويحللها:</p><ul><li>النفط: BS&amp;W ونسبة الملح، مقارنة بمواصفة التصدير.</li><li>الماء المنتج: النفط في الماء قبل تصريفه إلى البحر. التصريف منظَّم؛ ففي شمال شرق الأطلسي (OSPAR) مثلاً معيار الأداء 30 mg/L من النفط المشتت.</li><li>ماء الحقن: الأكسجين والمواد الصلبة. ويتابع أيضاً قسائم التآكل (corrosion coupons) ومعدلات حقن الكيماويات.</li></ul>`]),
crew_marine: E(['Marine & cargo superintendent', 'المشرف البحري ومسؤول الحمولة'], ['Cargo control room', 'غرفة التحكم بالحمولة'], [
`<p>Responsible for the vessel itself:</p><ul><li>Cargo and ballast tank sequence; hull stresses and stability (loading computer); draft and trim.</li><li>Inert-gas system, which keeps the oxygen in the tanks low; crude oil washing.</li><li>Leads offloading with the tanker master, together with mooring and hull integrity.</li></ul>`,
`<p>مسؤول عن السفينة نفسها:</p><ul><li>تسلسل خزانات الحمولة والصابورة (ballast)، وإجهادات البدن والاتزان (loading computer)، والغاطس والميلان الطولي (trim).</li><li>نظام الغاز الخامل الذي يُبقي الأكسجين منخفضاً داخل الخزانات، وغسيل الخزانات بالنفط الخام (COW).</li><li>يقود عملية التفريغ مع ربان الناقلة، ويتابع سلامة التثبيت والبدن.</li></ul>`]),
crew_crane: E(['Crane operator', 'مشغل الرافعة'], ['Pedestal crane cab', 'كابينة الرافعة'], [
`<p>Lifts containers, spares and chemicals from supply vessels and around the deck, following a <b>lift plan</b>. A banksman on deck gives the signals. Lifting stops when wind or the supply vessel motion exceed the crane limits.</p>`,
`<p>يرفع الحاويات وقطع الغيار والكيماويات من سفن الإمداد وعلى سطح المنشأة، وفق <b>خطة رفع (lift plan)</b>. يعطيه الإشارات مساعدٌ على السطح (banksman). وتتوقف عمليات الرفع إذا تجاوزت الرياح أو حركة سفينة الإمداد حدود الرافعة.</p>`]),
crew_deck: E(['Deck crew (roustabouts) & banksman', 'طاقم السطح (roustabouts) والـ banksman'], ['Main deck and laydown areas', 'السطح الرئيسي ومناطق التخزين'], [
`<p>Sling and guide loads, give crane signals (banksman), keep the deck tidy, and handle stores and waste. They also help the helideck team and handle the hawser and hose during offloading.</p>`,
`<p>يربطون الأحمال ويوجّهونها، ويعطي الـ banksman إشارات الرافعة، ويحافظون على نظافة السطح، ويتعاملون مع المخازن والنفايات. ويساعدون أيضاً فريق مهبط المروحيات، ويتعاملون مع حبل القطر والخرطوم أثناء التفريغ.</p>`]),
crew_hlo: E(['Helicopter landing officer (HLO)', 'ضابط هبوط المروحيات (HLO)'], ['Helideck', 'مهبط المروحيات'], [
`<p>In charge of every landing and take-off:</p><ul><li>Prepares the deck, checks wind and deck motion, and leads the <b>helideck fire team</b>.</li><li>Manages passengers, baggage and refuelling, and gives the pilot clearance (with the radio operator).</li></ul><p class="note">Use the <b>Take off</b> button on the helideck card to clear the helicopter. Take-off is refused in bad weather or during an ESD.</p>`,
`<p>مسؤول عن كل هبوط وإقلاع:</p><ul><li>يجهّز المهبط، ويتحقق من الرياح وحركة السطح، ويقود <b>فريق إطفاء المهبط</b>.</li><li>يدير الركاب والأمتعة والتزود بالوقود، ويعطي الطيار الإذن بالتنسيق مع مشغل الراديو.</li></ul><p class="note">استخدم زر <b>إقلاع</b> في بطاقة المهبط للسماح للمروحية بالإقلاع. يُرفض الإقلاع في الطقس السيئ أو أثناء ESD.</p>`]),
crew_rov: E(['ROV supervisor & pilots', 'مشرف وطيارو الـ ROV'], ['ROV control van, next to the LARS', 'غرفة تحكم الـ ROV بجوار الـ LARS'], [
`<p>Launch and fly the ROV from a control van: two pilots plus a supervisor per shift. Their work covers inspection (hull, chains, risers, trees) and intervention (valves, hot-stabs, choke inserts). They plan every dive with the subsea engineer.</p>`,
`<p>يُنزلون الـ ROV ويقودونه من غرفة تحكم (control van): طياران ومشرف في كل مناوبة. يشمل عملهم الفحص (البدن، السلاسل، الـ risers، الـ trees) والتدخل (الصمامات، الـ hot-stabs، قطع الـ choke). ويخططون لكل غطسة مع مهندس المعدات تحت البحر.</p>`]),
crew_medic: E(['Offshore medic', 'المسعف البحري'], ['Sick bay (accommodation)', 'العيادة (في مبنى السكن)'], [
`<p>Provides first aid and treatment, with telemedicine support from an onshore doctor. Runs health surveillance and hygiene checks, and is part of the emergency response team. Arranges medevac by helicopter when needed.</p>`,
`<p>يقدّم الإسعافات الأولية والعلاج، بدعم طبي عن بُعد من طبيب على البر. يتابع المراقبة الصحية وفحوص النظافة، وهو عضو في فريق الاستجابة للطوارئ. ويرتّب الإخلاء الطبي بالمروحية عند الحاجة.</p>`]),
tug: E(['Support (hold-back) tug', 'القاطرة المساندة (hold-back tug)'], ['Second vessel in tandem offloading', 'السفينة الثانية في التفريغ الترادفي'], [
`<p>In tandem offloading the shuttle tanker lies astern of the FPSO on the hawser. A conventional tanker (without dynamic positioning) has a <b>support tug</b> made fast to its stern. The tug pulls astern to keep the hawser tensioned and the tanker in line, so it cannot ride up on the FPSO. The tug also helps during approach and in an emergency disconnect.</p><p class="note">Tankers with DP (dynamic positioning) often offload without a hold-back tug, but a standby/support vessel is usually present.</p>`,
`<p>في التفريغ الترادفي تقف الناقلة المكوكية خلف الـ FPSO مربوطة بحبل القطر (hawser). وتُربط بمؤخرة الناقلة التقليدية (التي لا تملك تموضعاً ديناميكياً) <b>قاطرةٌ مساندة</b> تسحب للخلف، فيبقى حبل القطر مشدوداً والناقلة على الخط، ولا تندفع نحو الـ FPSO. وتساعد القاطرة أيضاً أثناء الاقتراب وفي الفصل الطارئ.</p><p class="note">الناقلات ذات الـ DP (التموضع الديناميكي) تفرّغ غالباً بدون قاطرة شدّ، لكن عادةً توجد سفينة مساندة/احتياط.</p>`]),
fielddata: E(['Field data and calibration', 'البيانات الحقلية والمعايرة'], ['Make the simulator reproduce a real field period', 'جعل المحاكي يطابق فترة من حقل حقيقي'], [
`<p>Load a production history (CSV) and pick a period. <b>Calibrate</b> then adjusts the model until it produces the same <b>oil, water and gas rates</b>, and therefore the same water cut and GOR, as the field in that period.</p>
<ul><li><b>Size factor:</b> the well productivity, choke capacity, flowline and riser friction, and separator volume are scaled together. This is like a field with more or larger wells of the same design.</li><li><b>Per well:</b> the water cut and GOR of each well are shifted until the rate-weighted values match the field.</li><li><b>Facilities:</b> compression, export, produced-water and injection capacity, and the number of gas turbines are sized for the new rates.</li></ul>
<p class="note"><b>Limitations:</b> this is a <b>single-period rate match</b>, not a full history match. Reservoir pressure, PVT, tubing and equipment curves stay generic, so pressures are indicative only. Volve data includes BHP and WHP, which are shown next to the model for comparison but are not fitted. Sodir rates are calendar-month averages, so downtime is included.</p>`,
`<p>حمّل تاريخ إنتاج (CSV) واختر فترة. عندها يعدّل زر <b>المعايرة</b> النموذج حتى ينتج <b>معدلات النفط والماء والغاز</b> نفسها التي أنتجها الحقل في تلك الفترة، وبالتالي نسبة الماء والـ GOR نفسيهما.</p>
<ul><li><b>معامل الحجم:</b> تُكبَّر معاً إنتاجية الآبار، وسعة الـ choke، واحتكاك الـ flowlines والـ riser، وحجم الفاصل. وهذا يشبه حقلاً فيه آبار أكثر أو أكبر بالتصميم نفسه.</li><li><b>لكل بئر:</b> تُزاح نسبة الماء والـ GOR لكل بئر حتى تطابق القيم الموزونة بالمعدل قيمَ الحقل.</li><li><b>المرافق:</b> تُحجَّم سعة الضغط والتصدير والماء المنتج والحقن، وعدد التوربينات الغازية، للمعدلات الجديدة.</li></ul>
<p class="note"><b>الحدود:</b> هذه <b>مطابقة معدلات لفترة واحدة</b>، وليست مطابقة تاريخية كاملة (history match). ضغط المكمن والـ PVT ومنحنيات الأنابيب والمعدات تبقى عامة، فالضغوط تقريبية فقط. بيانات Volve فيها BHP و WHP، وتُعرض بجانب النموذج للمقارنة دون أن تُطابَق. ومعدلات Sodir متوسطات شهرية تقويمية، فهي تشمل فترات التوقف.</p>`]),
pvt: E(['Reservoir fluid (PVT)', 'مائع المكمن (PVT)'], ['Black-oil properties from correlations', 'خصائص black-oil من الارتباطات'], [
`<p>When no laboratory PVT report is available, engineers estimate fluid properties from <b>empirical correlations</b> built on large sets of measured samples.</p>
<ul><li><b>Pb, Rs and Bo (at and below Pb):</b> Standing (1947), API Drilling and Production Practice.</li><li><b>Bo above Pb</b> through the oil compressibility co: Vasquez &amp; Beggs (1980), JPT, SPE-6719-PA.</li><li><b>Oil viscosity:</b> Beggs &amp; Robinson (1975), JPT, SPE-5434-PA for dead and saturated oil; Vasquez &amp; Beggs (1980) above Pb.</li><li><b>Gas:</b> pseudo-critical properties from Standing's natural-gas correlation; z-factor from Papay (1968, explicit); viscosity from Lee, Gonzalez &amp; Eakin (1966), JPT, SPE-1340-PA.</li></ul>
<p>Below Pb, gas comes out of solution: Rs and Bo fall and the oil becomes more viscous. Above Pb, the oil is compressed and Bo falls slowly.</p>
<p class="note">Typical errors of these correlations are several percent for Bo and larger for Pb and viscosity. They are least reliable outside their data range (Standing: about 16–64 °API, gas SG 0.59–0.95, 38–125 °C). A lab PVT report always takes precedence. <b>Use this fluid</b> sets Pb, Bo, Bg, oil density and the well GORs of the simulator.</p>`,
`<p>عند غياب تقرير PVT مخبري يقدّر المهندسون خصائص المائع من <b>ارتباطات تجريبية (correlations)</b> بُنيت على عدد كبير من العينات المقاسة.</p>
<ul><li><b>Pb و Rs و Bo (عند Pb وتحتها):</b> Standing (1947)، API Drilling and Production Practice.</li><li><b>Bo فوق Pb</b> عبر انضغاطية النفط co: Vasquez &amp; Beggs (1980)، JPT، SPE-6719-PA.</li><li><b>لزوجة النفط:</b> Beggs &amp; Robinson (1975)، JPT، SPE-5434-PA للنفط الميت والمشبع؛ و Vasquez &amp; Beggs (1980) فوق Pb.</li><li><b>الغاز:</b> الخواص شبه الحرجة من ارتباط Standing للغاز الطبيعي؛ ومعامل z من Papay (1968، صريح)؛ واللزوجة من Lee و Gonzalez و Eakin (1966)، JPT، SPE-1340-PA.</li></ul>
<p>تحت Pb يخرج الغاز من المحلول: ينخفض Rs و Bo وتزداد لزوجة النفط. وفوق Pb يُضغط النفط فينخفض Bo ببطء.</p>
<p class="note">الأخطاء المعتادة لهذه الارتباطات بضعة بالمئة في Bo، وأكبر في Pb واللزوجة. وهي أقل موثوقية خارج نطاق بياناتها (Standing: نحو 16–64 °API، وكثافة غاز 0.59–0.95، و 38–125 °C). تقرير PVT المخبري مقدَّم دائماً. زر <b>استخدم هذا المائع</b> يضبط في المحاكي Pb و Bo و Bg وكثافة النفط و GOR الآبار.</p>`]),
dca: E(['Decline-curve analysis (Arps)', 'تحليل منحنى الانخفاض (Arps)'], ['Fit, forecast, remaining reserves', 'مطابقة وتوقع واحتياطي متبقٍ'], [
`<p>Arps (1945), <i>Trans. AIME</i> 160: <b>q(t) = qi / (1 + b·Di·t)^(1/b)</b>. b = 0 is exponential decline (q = qi·e^(−Di·t)), 0 &lt; b &lt; 1 hyperbolic, b = 1 harmonic. The fit searches over b and Di and solves qi by least squares on ln q. The forecast runs to the economic limit (or 30 years) and gives the remaining reserves; EUR = produced + remaining.</p>
<ul><li>Start the fit <b>after the plateau</b> (move the period slider), during stable decline.</li><li>Changes in operations (new wells, workovers, injection, facility limits) break the assumption of a single decline. Fit only a consistent interval.</li><li>A small R² or a b close to 1 often means mixed regimes.</li></ul>
<p class="note">DCA is empirical. It is a check on simulation and material-balance estimates, not a substitute for them.</p>`,
`<p>Arps (1945)، <i>Trans. AIME</i> 160: <b>q(t) = qi / (1 + b·Di·t)^(1/b)</b>. b = 0 انخفاض أُسّي (q = qi·e^(−Di·t))، و 0 &lt; b &lt; 1 زائدي، و b = 1 توافقي. تبحث المطابقة في قيم b و Di، وتحسب qi بأقل المربعات على ln q. ويمتد التوقع حتى الحد الاقتصادي (أو 30 سنة) ليعطي الاحتياطي المتبقي؛ و EUR = المنتج + المتبقي.</p>
<ul><li>ابدأ المطابقة <b>بعد مرحلة الثبات (plateau)</b> بتحريك شريط الفترة، أثناء الانخفاض المستقر.</li><li>التغيرات التشغيلية (آبار جديدة، workovers، حقن، حدود المرافق) تكسر فرضية الانخفاض الواحد. طابِق فترة متجانسة فقط.</li><li>R² صغير أو قيمة b قريبة من 1 تعني غالباً اختلاط أنماط مختلفة.</li></ul>
<p class="note">تحليل الانخفاض تجريبي. هو أداة تحقق من تقديرات المحاكاة وموازنة المادة، وليس بديلاً عنها.</p>`]),
accommodation: E(['Accommodation & control room', 'السكن وغرفة التحكم'], ['People, control and safety', 'الأفراد والتحكم والسلامة'], [
`<p>Living quarters for the crew, the central control room, the helideck and the lifeboats. The control room runs the <b>process control</b> and <b>safety</b> systems: fire and gas detection, <b>PSD</b> (process shutdown) and <b>ESD</b> (emergency shutdown: wells isolated, blowdown to flare).</p>`,
`<p>مساكن الطاقم، وغرفة التحكم المركزية، ومهبط المروحيات، وقوارب النجاة. من غرفة التحكم تُدار أنظمة <b>التحكم بالعملية</b> و<b>السلامة</b>: كشف الحريق والغاز، و<b>PSD</b> (إيقاف العملية)، و<b>ESD</b> (الإيقاف الطارئ: عزل الآبار والتنفيس إلى الشعلة).</p>`]),
};
})();
