/* ===== Content data (Arabic + English technical terms) ===== */
const STAGES = [
  { id: 'reservoir', en: 'Reservoir', ar: 'المكمن', zone: 'تحت الأرض', tab: 'well',
    what: ['صخر مسامي (غالباً sandstone أو carbonate) يحتوي نفطاً وغازاً وماءً مضغوطين. الموائع لا "تُسحب" من المكمن؛ تتحرك لأن ضغط المكمن Pr أعلى من ضغط قاع البئر المتدفق Pwf. الفرق Pr − Pwf يسمى drawdown.',
           'مصدر الطاقة (drive mechanism) يحدد عمر الحقل: solution-gas drive (ينخفض الضغط بسرعة)، gas-cap drive، water drive (يحافظ على الضغط لكن يرفع water cut لاحقاً)، compaction.'],
    cond: [['Pr نموذجي', '≈ 0.43–0.50 psi لكل قدم عمق (مكمن بضغط طبيعي)'], ['T المكمن', '≈ 1–1.6°F لكل 100 قدم فوق درجة حرارة السطح'], ['القياس', 'PBU / DST / PLT / gauges في قاع البئر']],
    equip: ['لا معدات سطحية: القياس عبر downhole gauges واختبارات الضغط (build-up)'],
    watch: ['اتجاه Pr بمرور الوقت (material balance)', 'ارتفاع GOR (gas coning أو هبوط Pr تحت Pb)', 'ارتفاع water cut (water coning / breakthrough)'],
    fail: ['formation damage / skin عالٍ ← يقلل PI', 'sand production في الصخور الضعيفة', 'انخفاض Pr تحت bubble point ← تحرر غاز في المكمن وتدهور الإنتاج'] },

  { id: 'wellbore', en: 'Wellbore', ar: 'قاع البئر حتى السطح', zone: 'تحت الأرض', tab: 'well',
    what: ['المائع يدخل عبر perforations إلى الـ casing ثم يصعد في الـ tubing. الـ packer يعزل الـ annulus. صمام SCSSV (صمام أمان تحت السطح) يُغلق تلقائياً عند فقدان ضغط التحكم.',
           'في الـ tubing الضغط يضيع أساساً في الـ hydrostatic head (وزن عمود المائع) ثم الاحتكاك. عندما ينزل الضغط تحت Pb يتحرر الغاز، فتنخفض كثافة الخليط ويخف عمود الضغط (لهذا يتدفق البئر طبيعياً).',
           'إذا لم يكفِ ضغط المكمن لرفع المائع: artificial lift (ESP, gas lift, rod pump, PCP, plunger).'],
    cond: [['Tubing OD شائع', '2⅞" – 4½" (ID ≈ 2.44–3.96")'], ['العمق', '3,000 – 15,000 ft (أمثلة شائعة)'], ['ضغط الـ annulus', 'يُراقب دوماً كمؤشر لسلامة الـ casing/tubing']],
    equip: ['Casing + cement', 'Tubing + packer', 'SCSSV', 'Gas-lift mandrels / ESP / rods حسب طريقة الرفع'],
    watch: ['Pwf ومنحنى VLP مقابل IPR', 'ضغط tubing مقابل casing', 'amps/vibration في ESP، dynamometer في rod pump'],
    fail: ['ترسب scale / wax / asphaltene داخل tubing', 'sand fill فوق الـ perforations', 'تسريب tubing (ضغوط annulus متشابهة مع tubing)', 'gas lock في ESP'] },

  { id: 'wellhead', en: 'Wellhead & Choke', ar: 'رأس البئر والـ Choke', zone: 'السطح', tab: 'well',
    what: ['شجرة الإنتاج (Christmas tree): master valves + wing valve + swab valve. صمام SSV الهيدروليكي مربوط بنظام ESD ويُغلق عند ضغط عالٍ جداً أو منخفض جداً (PSHH / PSLL).',
           'الـ choke يتحكم في معدل الإنتاج ويفصل البئر عن ضغط المنشأة. في التدفق الحرج (critical flow: نسبة الضغط downstream/upstream < ≈ 0.55) لا يؤثر ضغط الفاصل على معدل البئر.',
           'هبوط الضغط الكبير عبر الـ choke يخفض درجة الحرارة (Joule–Thomson) ← خطر hydrates/wax. وإذا كان هناك رمل ← تآكل (erosion) الـ choke.'],
    cond: [['FWHP', '≈ 100 – 3,000 psi حسب الحقل'], ['تصنيف الضغط', 'API 6A: 2K/3K/5K/10K/15K'], ['Choke', 'fixed bean أو adjustable needle (بالـ 64ths of inch)']],
    equip: ['Master valves / wing valve / swab', 'SSV + ESD', 'Choke (positive/adjustable)', 'Pressure & temperature transmitters'],
    watch: ['FWHP و FLP (flowline pressure) ونسبتهما للتدفق الحرج', 'حجم الـ choke ومعدل الإنتاج', 'درجة الحرارة downstream (hydrate margin)'],
    fail: ['choke washout بسبب الرمل ← ارتفاع مفاجئ في المعدل وهبوط FWHP', 'تجمد/hydrate عند الـ choke', 'تسريب من flanges أو valve stem'] },

  { id: 'flowline', en: 'Flowline & Manifold', ar: 'خطوط التدفق والـ Manifold', zone: 'السطح', tab: 'trouble',
    what: ['الـ flowline ينقل مائعاً متعدد الأطوار (multiphase) من رأس كل بئر إلى الـ manifold. عند الـ manifold يمكن توجيه كل بئر إما إلى production header (مع باقي الآبار) أو إلى test header ثم test separator لقياس معدلات البئر منفرداً (well test) وتخصيص الإنتاج (allocation).',
           'أنماط التدفق (slug, stratified, annular) تحدد استقرار الفاصل: slug كبير يسبب ارتفاع مستوى مفاجئ وربما trip.',
           'Pigging دوري يزيل wax والسوائل المتراكمة. Corrosion inhibitor يُحقن غالباً عند رأس البئر.'],
    cond: [['سرعة التدفق', 'عادةً أقل من حد التآكل (erosional velocity) المحسوب بمعادلة API RP 14E'], ['اختبار الآبار', 'دوري (أسبوعي – شهري/ربع سنوي حسب سياسة الحقل)'], ['Pigging', 'launcher/receiver على الخط']],
    equip: ['Flowlines', 'Production & test headers', 'Test separator', 'Pig launcher/receiver', 'Chemical injection (inhibitor, demulsifier, anti-wax)'],
    watch: ['ΔP للخط (ارتفاعه يعني ترسب أو انسداد)', 'نتائج well test (GOR، water cut) مقارنةً بالسابق', 'حقن الكيماويات ومعدلاتها'],
    fail: ['slug flow', 'wax deposition وانسداد', 'corrosion (CO₂/H₂S/MIC)', 'تسريب/تجمد خطوط صغيرة'] },

  { id: 'separator', en: 'HP Separator', ar: 'الفصل (3-phase separator)', zone: 'السطح', tab: 'sep',
    what: ['فاصل أفقي (غالباً) ثلاثي الأطوار: الغاز يخرج من الأعلى، النفط من فوق الـ weir، الماء من الأسفل. الفصل يتم بالجاذبية (Stokes) بعد inlet device يكسر الزخم، مع mist extractor (mesh pad أو vane) لإزالة قطرات السائل من الغاز.',
           'التصميم يتحكم فيه قيدان: سعة الغاز (سرعة ترسب القطرات) و retention time للسائل (الزمن الكافي لفصل النفط والماء). لذلك يُقسم الفصل على مراحل (HP → LP) لتقليل shrinkage وفقد المكونات الخفيفة.',
           'التحكم: LIC (مستوى) و PIC (ضغط) مع LSHH/LSLL و PSV لحماية الوعاء.'],
    cond: [['ضغط HP نموذجي', '≈ 100 – 500 psig (يتحدد بضغط الغاز المصدَّر)'], ['Retention time', '≈ 3 – 10 دقائق (أطول للنفط الثقيل/البارد)'], ['Slenderness ratio', '3 – 5 (Lss/d) لأفقي']],
    equip: ['Inlet device', 'Weir + level controllers', 'Mist extractor', 'PSV', 'Sand jets/drains'],
    watch: ['مستوى النفط/الماء/interface', 'ضغط الفاصل واستقراره', 'carryover (سائل في الغاز) وcarry-under (غاز في النفط)'],
    fail: ['foaming', 'emulsion pad/rag layer عند الـ interface', 'تراكم رمل', 'slugging ← trip', 'PSV leaking'] },

  { id: 'treater', en: 'Treating', ar: 'المعالجة (Heater treater / Desalter)', zone: 'السطح', tab: 'sep',
    what: ['النفط الخارج من الفاصل يحمل ماءً مستحلباً (water-in-oil emulsion). كسر الاستحلاب يعتمد على أربع أدوات: كيماويات (demulsifier)، حرارة (تقلل اللزوجة وتضعف الفيلم المحيط بالقطرات)، زمن ترسب، وأحياناً مجال كهربائي (electrostatic coalescer).',
           'Heater treater: وعاء واحد فيه firetube + فصل + ترسب. في الحقول الكبيرة: FWKO + heater + electrostatic dehydrator، ثم desalter (غسل بماء عذب لتخفيف الملوحة).',
           'قاعدة Stokes: سرعة ترسب القطرة ∝ d² و Δρ ولا تتناسب عكسياً إلا مع اللزوجة μ؛ لذا رفع الحرارة (↓ μ) وتحسين التلاحم (↑ d) هما الرافعتان الرئيسيتان.'],
    cond: [['درجة التشغيل', '≈ 100 – 180°F (حسب الخام)'], ['مواصفات شائعة للتسليم', 'BS&W ≈ 0.5 – 1% (حسب العقد/خط الأنابيب)'], ['Salt بعد الـ desalter', 'غالباً ≤ ≈ 10 PTB لمصافي التكرير (تختلف حسب العقد)']],
    equip: ['FWKO', 'Heater treater / firetube', 'Electrostatic coalescer', 'Desalter + wash water', 'Demulsifier injection pump'],
    watch: ['BS&W عند الخروج (centrifuge أو online analyzer)', 'استهلاك الوقود ودرجة الحرارة', 'interface/rag layer'],
    fail: ['rag layer مستقر (ماء + نفط + مواد صلبة/surfactants)', 'burner flame-out', 'تآكل firetube', 'اختيار demulsifier غير مناسب'] },

  { id: 'stabilizer', en: 'Stabilization', ar: 'التثبيت (LP flash / Stabilizer)', zone: 'السطح', tab: 'store',
    what: ['خفض الضغط على مراحل حتى قرب الضغط الجوي يحرر المكونات الخفيفة (C1–C4) فيصبح الخام "مستقراً" ولا يفقد بخاراً في الخزانات. يُقاس ذلك بـ RVP/TVP.',
           'الغاز المتحرر من LP flash/tanks يُجمع بـ VRU (vapor recovery unit) بدل الحرق أو التنفيس. وإذا كان الخام حامضياً (H₂S) يُجرى stripping لخفض H₂S في السائل.',
           'هذه هي مرحلة shrinkage الحقيقية: حجم النفط في المكمن (مع الغاز المذاب) أكبر من حجمه في الخزان (STB). Bo = reservoir bbl لكل STB.'],
    cond: [['ضغط LP نموذجي', '≈ 10 – 50 psig'], ['RVP للخام', 'حسب المواصفة (مثلاً ≤ ≈ 10–12 psi لبعض العقود)'], ['H₂S في السائل', 'حسب عقد التسليم (غالباً ppm منخفض)']],
    equip: ['LP separator / flash drum', 'Stabilizer column (للحقول الكبيرة)', 'VRU compressor', 'Heat exchangers'],
    watch: ['RVP/TVP للخام', 'معدل غاز الـ LP والـ tanks', 'ضغط LP واستقراره'],
    fail: ['فقد بخار وانبعاثات من الخزانات', 'ضغط LP متذبذب ← carry-over', 'تجمد/hydrates في خطوط الغاز منخفض الضغط'] },

  { id: 'gas', en: 'Gas handling', ar: 'معالجة الغاز والحرق', zone: 'السطح', tab: 'gas',
    what: ['الغاز يمر على scrubber (KO drum) لإزالة السوائل، ثم ضاغط (reciprocating أو screw أو centrifugal) يرفعه إلى ضغط التصدير/الحقن/الوقود. يُجفف بـ TEG contactor لتفادي hydrates وتآكل، ويُحلّى بـ amine عند وجود H₂S/CO₂.',
           'استعمالات الغاز: fuel gas للحقل، gas lift، إعادة حقن، تصدير عبر خط أنابيب، أو معالجة NGL. أي فائض أو حالة طوارئ يذهب إلى flare عبر KO drum.',
           'الحرق الروتيني مُقيَّد تنظيمياً وبيئياً؛ مبادرة البنك الدولي "Zero Routine Flaring by 2030" معروفة (مؤكَّد).'],
    cond: [['مواصفة الماء في الغاز', 'غالباً ≈ 7 lb لكل MMscf في عقود خطوط أنابيب أمريكية (تختلف)'], ['Compression ratio/stage', 'عادةً ≤ ≈ 4'], ['Flare', 'KO drum + pilot + smokeless tip']],
    equip: ['Inlet scrubber', 'Compressor + intercoolers', 'TEG contactor/regenerator', 'Amine unit (إن لزم)', 'Flare KO drum + stack'],
    watch: ['درجة حرارة التفريغ (discharge T)', 'ضغط الشفط والتفريغ', 'dew point للماء', 'معدل الحرق'],
    fail: ['liquid carryover إلى الضاغط (تلف ميكانيكي)', 'hydrates', 'تآكل بسبب CO₂/H₂S + ماء', 'surge في centrifugal'] },

  { id: 'water', en: 'Produced water', ar: 'معالجة مياه الإنتاج', zone: 'السطح', tab: 'gas',
    what: ['الماء المصاحب يزداد مع عمر الحقل ويصبح غالباً أكبر مكوّن بالحجم. يمر على skim tank/API separator ثم CPI أو hydrocyclone أو IGF لإزالة النفط المتبقي، ثم filters قبل الحقن (waterflood) أو التخلص (disposal well).',
           'مقاييس الجودة: oil-in-water (OIW)، TSS، حجم الجسيمات، البكتيريا (SRB)، وميل الترسب (scale index). المتطلبات الدقيقة تعتمد على نفاذية الطبقة المستقبِلة والتنظيم المحلي.',
           'الفصل هنا أيضاً Stokes: أصغر قطرة نفط تُزال = f(Q/A) أي معدل التدفق إلى مساحة السطح.'],
    cond: [['OIW للتصريف البحري', '≈ 30 mg/L متوسط شهري (OSPAR 2001/1)'], ['حقن ماء', 'أهداف TSS/OIW صغيرة جداً وتعتمد على النفاذية (تُحدد بـ core-flood وفلترة)'], ['Water cut', 'يزداد مع الزمن في الحقول الناضجة']],
    equip: ['FWKO / skim tank', 'Hydrocyclones / IGF / CPI', 'Filters', 'Injection pumps', 'Chemical dosing (scale/biocide/oxygen scavenger)'],
    watch: ['OIW و TSS', 'معدل الحقن والضغط (injectivity)', 'تحاليل الكيمياء (Ca/Ba/Sr/SO₄/Fe)'],
    fail: ['scale (CaCO₃, BaSO₄)', 'سد الـ filters وهبوط injectivity', 'souring (SRB) وإنتاج H₂S', 'نفط زائد في الماء بعد upset'] },

  { id: 'tank', en: 'Storage tanks', ar: 'وحدات التخزين (الخزانات)', zone: 'السطح', tab: 'store',
    what: ['خزانات أسطوانية (API 650) fixed-roof أو floating-roof. تعمل كـ surge buffer بين الإنتاج المستمر والتسليم المتقطع (شاحنات/سفن). في بعض الحقول يوجد wash tank / gun barrel للترسب النهائي.',
           'الحجم الفعلي لا يُقرأ من مقياس الارتفاع مباشرة: يُحسب من جدول المعايرة (strapping table) ثم يصحح للماء الحر ودرجة الحرارة (API MPMS Ch. 11.1) و BS&W.',
           'Tank bottoms: ماء ورواسب وطين تتجمع تحت النفط وتحتاج تنظيفاً دورياً.'],
    cond: [['سعة (bbl/ft)', '0.1399 × d² (d بالقدم)'], ['تعبئة آمنة', 'عادةً ≈ 85–95% من الارتفاع الاسمي حسب وضع الـ high-high level'], ['حرارة', 'تسخين بملفات للنفوط الشمعية']],
    equip: ['Tanks + gauging (radar/ATG + manual dip)', 'High/high-high level alarms', 'Heating coils', 'Vapor recovery', 'Pumps'],
    watch: ['مستويات الخزان واتجاه الماء الحر', 'BS&W في القاع', 'ضغط/vacuum الـ breather'],
    fail: ['overfill', 'vapor losses', 'تراكم sludge', 'roof landing/sinking في floating roof', 'صاعقة/حريق'] },

  { id: 'lact', en: 'LACT / Custody transfer', ar: 'القياس والتسليم (LACT)', zone: 'السطح', tab: 'store',
    what: ['وحدة LACT (Lease Automatic Custody Transfer): sampler يأخذ عينة تمثيلية، BS&W monitor، meter (PD/turbine/Coriolis)، حساسات حرارة وضغط، وflow computer. إذا ارتفع BS&W فوق الحد يفتح divert valve ويرد الخام للمعالجة.',
           'الحساب التجاري: Gross → (تصحيح حرارة CTL) → GSV → (طرح BS&W) → NSV. الـ meter يُعاير دورياً بـ prover (API MPMS Ch. 4).',
           'هذه نقطة المال: خطأ 0.1% في الحجم أو BS&W يُترجم إلى مبالغ كبيرة.'],
    cond: [['Meter factor', 'يُحدَّث بعد كل proving'], ['BS&W cut-off', 'حسب العقد، غالباً ≈ 0.5 – 1%'], ['مرجع', 'API MPMS Ch. 4 (proving), 8 (sampling), 11.1 (volume correction), 12 (calculations)']],
    equip: ['Strainer/air eliminator', 'Meter + prover connections', 'Sampler + BS&W probe', 'Flow computer', 'Divert valve'],
    watch: ['meter factor drift', 'تمثيلية العينة', 'divert events'],
    fail: ['sampler fouling', 'تحيّز BS&W probe', 'تسرب هواء ← خطأ في القياس'] },

  { id: 'export', en: 'Export', ar: 'التصدير (Pipeline / Truck / Tanker)', zone: 'التصدير', tab: 'store',
    what: ['مضخات نقل ترفع الضغط للتغلب على احتكاك الخط وفرق الارتفاع. الخط يعمل غالباً في تدفق مضطرب؛ اللزوجة ودرجة الحرارة وpour point تحدد إن كانت هناك حاجة لتسخين أو drag reducer.',
           'بدائل: شاحنات (road tankers) من loading rack، سكك حديدية، أو تحميل بحري (SPM / jetty). كل مسار يمر بقياس تجاري ونظام SCADA/leak detection.',
           'Batching ومرور pigs لتنظيف الخط ومراقبة التآكل.'],
    cond: [['سرعة نموذجية للخام', '≈ 3 – 7 ft/s (قد تقل في الخطوط الطويلة)'], ['MAOP', 'يحدد عدد محطات الضخ'], ['Pour point', 'يحدد الحاجة للتسخين/الحقن بالكيماويات']],
    equip: ['Transfer pumps', 'Pipeline + pig traps', 'Loading rack/SPM', 'SCADA + leak detection (CPM)'],
    watch: ['ΔP/mile مقابل التصميم', 'درجة حرارة الخط (wax)', 'ضغط التفريغ مقابل MAOP'],
    fail: ['wax gelling عند توقف الضخ في الشتاء', 'تسرب/تآكل', 'cavitation في المضخات'] }
];

const TROUBLE = [
  { id: 'emul', stage: 'treater', t: 'استحلاب شديد / rag layer', sym: 'BS&W مرتفع في الخروج، interface غير واضح، طبقة رمادية سميكة بين النفط والماء.',
    cause: ['Surfactants طبيعية (asphaltenes, resins, naphthenic acids) أو كيماويات مضافة', 'جسيمات دقيقة صلبة (fines, corrosion products) تثبّت القطرات', 'خلط شديد (choke ΔP عالٍ، مضخة shear عالٍ)', 'حرارة منخفضة / زمن بقاء قصير / demulsifier غير مناسب'],
    check: ['Bottle test بالخام الحقيقي عند درجة حرارة التشغيل', 'قياس الـ interface (level bridle / sampling taps)', 'تحليل الـ rag (ماء%، صلب%، فلزات)'],
    fix: ['تغيير/تحسين demulsifier وجرعته ونقطة الحقن (قبل الـ choke أو upstream)', 'رفع الحرارة أو زيادة retention time', 'إزالة الصلب/تحسين الفلترة، وتخفيف shear'] },
  { id: 'foam', stage: 'separator', t: 'Foaming في الفاصل', sym: 'مستوى سائل غير مستقر، liquid carryover في الغاز، trip عند LSHH.',
    cause: ['سرعة تحرر غاز عالية (انخفاض ضغط مفاجئ)', 'surfactants / كيماويات حقل / corrosion inhibitor زائد', 'لزوجة نفط عالية تحبس الفقاعات', 'ملوثات (oil-based mud, fines)'],
    check: ['زجاجة مستوى (sight glass) أو عينة', 'اختبار foam height/ half-life في المختبر', 'تغيّر في ضغط الفاصل مقابل المعدل'],
    fix: ['حقن anti-foam بكمية مضبوطة (الجرعة الزائدة قد تفاقم المشكلة)', 'خفض المعدل أو رفع الضغط', 'زيادة retention time / إضافة internals (vane/ plates) في التصميم'] },
  { id: 'slug', stage: 'flowline', t: 'Slugging', sym: 'تذبذب مستوى الفاصل، فتح/إغلاق متكرر لـ PSV، تذبذب ضغط الغاز.',
    cause: ['terrain slugging في خط متعرج', 'hydrodynamic slugging عند معدلات منخفضة', 'pigging (slug أمام الـ pig)', 'severe slugging عند riser'],
    check: ['سجل ضغط/مستوى زمني (trend)', 'GLR ومعدل الخط مقابل خريطة أنماط التدفق', 'حساب حجم الـ slug مقابل سعة الفاصل'],
    fix: ['slug catcher أو فاصل أكبر', 'ضبط choke/ زيادة معدل الغاز', 'جدولة pigging مع تجهيز الفاصل'] },
  { id: 'hydrate', stage: 'wellhead', t: 'Hydrates عند الـ choke أو الخطوط', sym: 'هبوط مفاجئ في التدفق، تجمد خارجي، ارتفاع ΔP عبر الـ choke.',
    cause: ['ضغط عالٍ + حرارة منخفضة + ماء حر + غاز', 'Joule–Thomson عبر choke', 'إيقاف طويل بدون inhibitor'],
    check: ['مقارنة T التشغيل مع منحنى تكوّن hydrate للغاز الحقيقي', 'تحقق من حقن MeOH/MEG وإنتاجيته', 'حرارة downstream الـ choke'],
    fix: ['حقن methanol/MEG (راجع الحاسبة)', 'تسخين upstream الـ choke أو عزل الخط', 'Depressurize تدريجياً لإذابة السدة (إجراء أمان صارم)'] },
  { id: 'wax', stage: 'flowline', t: 'ترسب Wax (Paraffin)', sym: 'ΔP يرتفع تدريجياً، انخفاض معدل الإنتاج، pig يخرج بكمية شمع كبيرة.',
    cause: ['درجة الحرارة تحت WAT (wax appearance temperature)', 'نفط عالي المحتوى بالـ n-paraffins', 'توقف تدفق طويل ← gelling تحت pour point'],
    check: ['قياس WAT/pour point (DSC أو cross-polarized microscopy، ASTM D97 لـ pour point)', 'حرارة الخط الفعلية', 'تحليل ما يخرجه الـ pig'],
    fix: ['pigging منتظم', 'عزل/تسخين الخط', 'wax inhibitors / pour point depressants', 'hot oiling أو solvent soak للـ tubing'] },
  { id: 'scale', stage: 'wellbore', t: 'ترسب Scale', sym: 'هبوط الإنتاج أو PI، تراكم قشرة في tubing/choke/مضخات، ارتفاع ضغط الحقن.',
    cause: ['خلط مياه غير متوافقة (SO₄ من ماء البحر + Ba/Sr/Ca)', 'انخفاض ضغط يحرر CO₂ ← CaCO₃', 'تغير حرارة'],
    check: ['تحليل ماء كامل + scale prediction', 'تحليل XRD للقشرة', 'مراقبة residual inhibitor'],
    fix: ['scale inhibitor squeeze أو حقن مستمر', 'acid job للـ carbonate scale', 'تجنب خلط الماء غير المتوافق / sulfate removal'] },
  { id: 'corr', stage: 'flowline', t: 'تآكل (CO₂/H₂S/MIC)', sym: 'تسرب، فقد سماكة في ILI/UT، حديد ذائب مرتفع في الماء.',
    cause: ['CO₂ + ماء (sweet corrosion)', 'H₂S (sour) مع SSC/HIC', 'بكتيريا SRB (MIC)', 'سرعات عالية تكسر الفيلم الواقي'],
    check: ['coupons وprobes، Fe count', 'تفتيش ILI/UT', 'pH وضغط جزئي لـ CO₂/H₂S'],
    fix: ['corrosion inhibitor مع جدولة تحكم', 'biocide + pigging', 'اختيار مواد مناسبة (NACE MR0175/ISO 15156 لبيئات sour)'] },
  { id: 'sand', stage: 'wellhead', t: 'إنتاج الرمل', sym: 'تآكل choke/مرفقات، تراكم رمل بالفاصل، ضوضاء/اهتزاز، ارتفاع BS&W.',
    cause: ['drawdown عالٍ يفوق قوة الصخر', 'انخفاض الضغط/تغير الإجهادات مع الزمن', 'ارتفاع water cut يفكك الربط'],
    check: ['sand monitor acoustic', 'أخذ عينات من الفاصل', 'مقارنة معدل الرمل بحدود التآكل'],
    fix: ['خفض الـ drawdown/معدل', 'gravel pack / screens / chemical consolidation', 'sand jets وcyclones على السطح'] },
  { id: 'bsw', stage: 'lact', t: 'BS&W مرتفع عند LACT', sym: 'divert متكرر، رفض شحنة، خلاف في الكمية.',
    cause: ['upset في الـ heater treater', 'ماء حر في tank bottom يُسحب مع النفط', 'مستوى سحب (suction) منخفض جداً'],
    check: ['centrifuge test (ASTM D4007) وKarl Fischer (ASTM D4377/D6304)', 'مستوى الماء الحر في الخزان', 'مراجعة تشغيل الـ treater (T، demulsifier)'],
    fix: ['تصريف الماء الحر قبل التسليم', 'تثبيت التسخين/الكيماويات', 'رفع نقطة السحب أو recirculation'] },
  { id: 'esp', stage: 'wellbore', t: 'ESP trip أو gas lock', sym: 'amps منخفضة/متذبذبة، تحميل منخفض، trip على under-load.',
    cause: ['free gas عند intake (Pwf < Pb)', 'ارتفاع حرارة المحرك', 'رمل/صلب يتآكل impellers', 'جهد غير مستقر'],
    check: ['منحنى amps/HZ', 'حساب gas fraction عند intake', 'حرارة المحرك ومقاومة العزل'],
    fix: ['gas separator/handler', 'خفض معدل السحب أو رفع Pwf', 'VSD وإعادة ضبط الحدود'] },
  { id: 'glinst', stage: 'wellbore', t: 'عدم استقرار Gas lift (heading)', sym: 'تذبذب دوري في المعدل والضغط، استهلاك غاز مرتفع.',
    cause: ['حقن عبر valve واحد بضغط غير كافٍ', 'تذبذب بين casing وtubing (casing heading)', 'ضغط غاز الحقن متغير'],
    check: ['trend ضغط tubing/casing ومعدل الحقن', 'two-pen chart / surveys', 'تحقق من الـ valves بالـ wireline'],
    fix: ['تثبيت ضغط الحقن + choke حقن مناسب', 'تصميم valves (orifice) أصح', 'تحسين عمق نقطة الحقن'] },
  { id: 'srp', stage: 'wellbore', t: 'Fluid pound / Gas interference (rod pump)', sym: 'dynamometer card غير ممتلئ، ضربات ميكانيكية.',
    cause: ['pump-off (معدل السحب أعلى من الاتجاه)', 'غاز حر يدخل المضخة', 'سرعة ضخ عالية'],
    check: ['dynamometer card (fillage)', 'مستوى السائل (echometer)', 'gas anchor وعمق الـ intake'],
    fix: ['pump-off controller أو تقليل SPM', 'gas separator/anchor', 'تعميق المضخة أو تغيير stroke'] },
  { id: 'tankloss', stage: 'tank', t: 'فقد بخار وارتفاع مستويات الخزان', sym: 'روائح/انبعاثات، تذبذب ضغط breather، مستويات غير متوقعة.',
    cause: ['خام غير مستقر (RVP مرتفع)', 'تسخين زائد', 'لا يوجد VRU', 'تدفق غاز من الفاصل مع النفط (dump valve يتعطل)'],
    check: ['قياس RVP/TVP', 'عمل الـ dump valve والمستوى بالفاصل', 'قراءة معدل الغاز إلى VRU'],
    fix: ['LP stage إضافية أو stabilizer', 'تركيب VRU', 'تحسين تحكم المستوى والـ dump'] },
  { id: 'inject', stage: 'water', t: 'هبوط injectivity', sym: 'ضغط الحقن يرتفع عند نفس المعدل.',
    cause: ['جسيمات/زيت في الماء يسد الوجه', 'scale أو بكتيريا', 'ضغط يتجاوز fracture pressure أو تشكل fractures'],
    check: ['Hall plot / ΔP vs. cumulative volume', 'تحليل OIW/TSS والفلاتر', 'membrane filtration test'],
    fix: ['رفع جودة الماء (فلاتر/كيماويات)', 'acidizing/ backflush للبئر', 'تقييم الحقن تحت ضغط الكسر'] }
];

const AL_DATA = [
  { k: 'srp', n: 'Sucker rod pump (SRP)', ar: 'مضخة قضبان' },
  { k: 'esp', n: 'ESP', ar: 'مضخة غاطسة كهربائية' },
  { k: 'gl',  n: 'Gas lift', ar: 'رفع بالغاز' },
  { k: 'pcp', n: 'PCP', ar: 'مضخة تجويف متقدم' },
  { k: 'pl',  n: 'Plunger lift', ar: 'مكبس (plunger)' }
];

const GLOSS = [
  ['API gravity', 'مقياس كثافة النفط: 141.5/SG − 131.5. أعلى API = أخف.'],
  ['BS&W', 'Basic Sediment & Water: نسبة الماء والرواسب في الخام (حجماً).'],
  ['STB', 'Stock-tank barrel: برميل عند 60°F و14.696 psia بعد خروج الغاز.'],
  ['Bo', 'Oil formation volume factor: bbl مكمن لكل STB.'],
  ['Rs', 'Solution GOR: scf غاز مذاب لكل STB عند ضغط ودرجة معينة.'],
  ['GOR / GLR', 'Gas-oil ratio / gas-liquid ratio (scf/STB أو scf/bbl سائل).'],
  ['Pb', 'Bubble point: الضغط الذي يبدأ عنده تحرر الغاز.'],
  ['PI / J', 'Productivity index: STB/d لكل psi drawdown (فوق Pb).'],
  ['IPR', 'Inflow Performance Relationship: العلاقة بين معدل المكمن و Pwf.'],
  ['VLP / TPR', 'Vertical Lift Performance: Pwf المطلوب لرفع معدل معين عبر الـ tubing.'],
  ['Nodal analysis', 'تقاطع IPR مع VLP يحدد نقطة التشغيل.'],
  ['Pwf / FBHP', 'Flowing bottom-hole pressure.'],
  ['FWHP / FTHP', 'Flowing wellhead/tubing-head pressure.'],
  ['Skin', 'معامل ضرر/تحسين قرب البئر (موجب = ضرر).'],
  ['Drawdown', 'Pr − Pwf.'],
  ['Xmas tree', 'مجموعة صمامات رأس البئر: master/wing/swab.'],
  ['SCSSV / SSV', 'صمامات أمان تحت/فوق السطح تُغلق آلياً.'],
  ['Choke', 'مقاوم تدفق يتحكم في المعدل ويخفض الضغط.'],
  ['Critical flow', 'تدفق صوتي عبر choke لا يتأثر بالضغط downstream.'],
  ['Manifold', 'تجميع وتوزيع تدفق عدة آبار (production/test header).'],
  ['Test separator', 'فاصل لقياس معدلات بئر واحد.'],
  ['Separator (2/3-phase)', 'وعاء يفصل غاز/سائل (ثنائي) أو غاز/نفط/ماء (ثلاثي).'],
  ['FWKO', 'Free-water knockout: يفصل الماء الحر قبل المعالجة.'],
  ['Heater treater', 'وعاء بـ firetube يكسر الاستحلاب بالحرارة.'],
  ['Desalter', 'غسل الخام بماء عذب لتقليل الملح.'],
  ['Demulsifier', 'كيماوي يكسر الاستحلاب ويسرّع تلاحم القطرات.'],
  ['PTB', 'Pounds of salt per thousand barrels.'],
  ['Retention time', 'زمن بقاء السائل في الوعاء = حجم السائل/المعدل.'],
  ['Mist extractor', 'mesh/vane لإزالة قطرات السائل من الغاز.'],
  ['Slug', 'دفعة سائل كبيرة في خط متعدد الأطوار.'],
  ['Pigging', 'تمرير جهاز تنظيف/فحص في الخط.'],
  ['Shrinkage', 'نقص حجم النفط من المكمن إلى الخزان بسبب تحرر الغاز.'],
  ['RVP / TVP', 'Reid / true vapor pressure: ضغط بخار الخام.'],
  ['Flash', 'تبخر مفاجئ عند خفض الضغط.'],
  ['VRU', 'Vapor recovery unit: يجمع بخار الخزانات/LP.'],
  ['Scrubber / KO drum', 'وعاء يفصل السوائل من الغاز قبل الضغط أو الحرق.'],
  ['TEG', 'Triethylene glycol لتجفيف الغاز.'],
  ['Amine', 'محلول يزيل H₂S/CO₂ (sweetening).'],
  ['Flare', 'حرق آمن للغاز الزائد أو الطارئ.'],
  ['PSV / PRV', 'Pressure safety/relief valve: حماية الوعاء من الضغط الزائد.'],
  ['ESD', 'Emergency shutdown system.'],
  ['LACT', 'Lease automatic custody transfer.'],
  ['Prover', 'جهاز معايرة عداد التدفق.'],
  ['TOV / GOV / GSV / NSV', 'Total observed / gross observed / gross standard / net standard volume.'],
  ['CTL / VCF', 'Correction for temperature of liquid: معامل تصحيح الحجم إلى 60°F.'],
  ['Tank bottoms', 'ماء ورواسب في قاع الخزان.'],
  ['Wax / WAT', 'ترسب البارافين؛ WAT = درجة ظهور الشمع.'],
  ['Pour point', 'أدنى درجة يبقى عندها الخام سائلاً.'],
  ['Hydrate', 'بلورات ماء + غاز تسد الخطوط.'],
  ['Scale', 'ترسب أملاح (CaCO₃, BaSO₄...).'],
  ['MIC', 'Microbiologically influenced corrosion.'],
  ['ESP', 'Electric submersible pump.'],
  ['SRP / PCP', 'Sucker-rod pump / Progressing cavity pump.'],
  ['Gas lift', 'حقن غاز في tubing لتخفيف العمود.'],
  ['Plunger lift', 'مكبس يرفع سائلاً بدفعات باستعمال طاقة الغاز.'],
  ['OIW / TSS', 'Oil-in-water / total suspended solids.'],
  ['IGF / CPI', 'Induced gas flotation / corrugated plate interceptor.'],
  ['Flowback', 'عودة سائل الـ frac بعد الشغل.'],
  ['Proppant', 'مادة تدعيم تبقي الشقوق مفتوحة.'],
  ['Breaker', 'مادة تكسر بوليمر gel بعد الشغل.'],
  ['Residue', 'مادة غير ذائبة متبقية من البوليمر بعد الكسر.']
];

const REFS = [
  ['Vogel, J.V. (1968). Inflow Performance Relationships for Solution-Gas Drive Wells. JPT 20(1): 83–92. DOI 10.2118/1476-PA', 'مرتفعة'],
  ['Standing, M.B. (1947). A Pressure-Volume-Temperature Correlation for Mixtures of California Oils and Gases. Drilling and Production Practice, API.', 'مرتفعة (بدون DOI)'],
  ['Beggs, H.D., Robinson, J.R. (1975). Estimating the Viscosity of Crude Oil Systems. JPT 27(9): 1140–1141. DOI 10.2118/5434-PA', 'مرتفعة'],
  ['Beggs, H.D., Brill, J.P. (1973). A Study of Two-Phase Flow in Inclined Pipes. JPT 25(5): 607–617. DOI 10.2118/4007-PA', 'مرتفعة'],
  ['Hagedorn, A.R., Brown, K.E. (1965). Experimental Study of Pressure Gradients Occurring During Continuous Two-Phase Flow in Small-Diameter Vertical Conduits. JPT 17(4): 475–484. DOI 10.2118/940-PA', 'مرتفعة'],
  ['Gilbert, W.E. (1954). Flowing and Gas-Lift Well Performance. Drilling and Production Practice, API. (وكذلك Ros، Baxendell، Achong كما تُذكر في كتب Production Engineering)', 'متوسطة: الثوابت تُنقل من مراجع ثانوية؛ تحقق منها'],
  ['Clegg, J.D., Bucaram, S.M., Hein, N.W. (1993). Recommendations and Comparisons for Selecting Artificial-Lift Methods. JPT 45(12): 1128–1167. DOI 10.2118/24834-PA', 'متوسطة–مرتفعة'],
  ['Hammerschmidt, E.G. (1934). Formation of Gas Hydrates in Natural Gas Transmission Lines. Ind. Eng. Chem. 26(8): 851–855.', 'متوسطة–مرتفعة'],
  ['Arnold, K., Stewart, M. Surface Production Operations, Vol. 1: Design of Oil-Handling Systems and Facilities. Gulf Professional Publishing.', 'مرتفعة (الكتاب)؛ أرقام المعادلات تختلف بين الطبعات'],
  ['GPSA Engineering Data Book (Gas Processors Suppliers Association).', 'مرتفعة'],
  ['API MPMS Chapter 11.1 (Temperature and Pressure Volume Correction Factors for Generalized Crude Oils...)؛ Ch. 4 (Proving); Ch. 8 (Sampling); Ch. 12 (Calculation).', 'مرتفعة (العناوين)؛ هذه الأداة تستخدم صيغة مبسطة لـ VCF وليس الجداول الكاملة'],
  ['API 12J (Oil & Gas Separators); API 650 (Welded Tanks); API 6A (Wellhead & Tree Equipment); API RP 14E (Piping erosional velocity).', 'مرتفعة'],
  ['ASTM D4007 (BS&W centrifuge), D4377/D6304 (Karl Fischer water in crude), D97 (pour point), D287/D1298 (API gravity).', 'مرتفعة'],
  ['OSPAR Recommendation 2001/1 (30 mg/L oil in produced water, monthly average).', 'مرتفعة'],
  ['Richardson, J.F., Zaki, W.N. (1954). Sedimentation and fluidisation: Part I. Trans. Inst. Chem. Eng. 32: 35–53. (تصحيح التزاحم لهبوط الحبيبات)', 'مرتفعة'],
  ['Schiller, L., Naumann, A. (1935). Über die grundlegenden Berechnungen bei der Schwerkraftaufbereitung. Z. Ver. Dtsch. Ing. 77: 318–320. (معامل السحب)', 'متوسطة: الصفحات من الذاكرة'],
  ['Faxén, H. (1922). Der Widerstand gegen die Bewegung einer starren Kugel in einer zähen Flüssigkeit, die zwischen zwei parallelen ebenen Wänden eingeschlossen ist. Ann. Phys. 68: 89–119. (تأثير جدران الشق)', 'متوسطة: التفاصيل من الذاكرة'],
  ['Cross, M.M. (1965). Rheology of non-Newtonian fluids: a new flow equation for pseudoplastic systems. J. Colloid Sci. 20: 417–437.', 'متوسطة–مرتفعة'],
  ['Barbati, A.C., Desroches, J., Robisson, A., McKinley, G.H. (2016). Complex fluids and hydraulic fracturing. Annu. Rev. Chem. Biomol. Eng. 7: 415–453.', 'متوسطة: لا DOI لأنني غير متأكد منه'],
  ['Lee, W.J. (1982). Well Testing (SPE Textbook Series Vol. 1). (نصف قطر الاستقصاء ‎r = √(k·t/(948·φ·μ·c_t))‎)', 'متوسطة–مرتفعة'],
  ['Wattenbarger, R.A., El-Banbi, A.H., Villegas, M.E., Maggard, J.B. (1998). Production analysis of linear flow into fractured tight gas wells. SPE 39931.', 'متوسطة: الرقم من الذاكرة'],
  ['Papay, J. (1968). Z-factor correlation (Hungarian oil & gas institute report).', 'متوسطة: أنا غير متأكد من التفاصيل الببليوغرافية؛ الصيغة شائعة في الكتب']
];
